### ISSUE TITLE
Server crash seems to be caused by Shield Library?

### ISSUE THREAD

**Issue by Sindavar** [CrimsonDawn45/Fabric-Shield-Lib#12]
`Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraft/class_638
at me.crimsondawn45.fabricshieldlib.object.AbstractShield.<init>(AbstractShield.java:85) ~[FabricShieldLib-v1.2.1-1.16.2.jar:?]
at rionlion100.extrashields.CustomShield.<init>(CustomShield.java:9) ~[extrashields-0.3.1+1.16.2.jar:?]
at rionlion100.extrashields.ExtraShields.registerShield(ExtraShields.java:34) ~[extrashields-0.3.1+1.16.2.jar:?]
at rionlion100.extrashields.ExtraShields.onInitialize(ExtraShields.java:61) ~[extrashields-0.3.1+1.16.2.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
... 17 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
at me.crimsondawn45.fabricshieldlib.object.AbstractShield.<init>(AbstractShield.java:85) ~[FabricShieldLib-v1.2.1-1.16.2.jar:?]
at rionlion100.extrashields.CustomShield.<init>(CustomShield.java:9) ~[extrashields-0.3.1+1.16.2.jar:?]
at rionlion100.extrashields.ExtraShields.registerShield(ExtraShields.java:34) ~[extrashields-0.3.1+1.16.2.jar:?]
at rionlion100.extrashields.ExtraShields.onInitialize(ExtraShields.java:61) ~[extrashields-0.3.1+1.16.2.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
... 17 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
at me.crimsondawn45.fabricshieldlib.object.AbstractShield.<init>(AbstractShield.java:85) ~[FabricShieldLib-v1.2.1-1.16.2.jar:?]
at rionlion100.extrashields.CustomShield.<init>(CustomShield.java:9) ~[extrashields-0.3.1+1.16.2.jar:?]
at rionlion100.extrashields.ExtraShields.registerShield(ExtraShields.java:34) ~[extrashields-0.3.1+1.16.2.jar:?]
at rionlion100.extrashields.ExtraShields.onInitialize(ExtraShields.java:61) ~[extrashields-0.3.1+1.16.2.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
... 17 more`

**Comment by CrimsonDawn45** [comment]
Hmm, Interesting I'll look into this soon. I am working on getting this library back on track and Hopefully adding more functionality.

**Comment by CrimsonDawn45** [comment]
Yeah, I think that's just because the mod wasn't properly updated and we were just kind of increasing the version without remapping everything.

**Comment by CrimsonDawn45** [comment]
There are a lot of issues with this project, but I'll try to see if I can get an alpha release out to patch that.

**Comment by CrimsonDawn45** [comment]
As of version v1.3.1a, this bug seems to be fixed I have done testing and haven't had any issues if there are still issues it might be caused by ExtraShield's being outdated.
