### ISSUE TITLE
Error when running on a server. (1.16.5)

### ISSUE THREAD

**Issue by px01tv** [CrimsonDawn45/Fabric-Shield-Lib#23]
```
Caused by: java.lang.RuntimeException: Cannot load class net.minecraft.client.world.ClientWorld in environment type SERVER
	at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:75) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:152) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
	at me.crimsondawn45.fabricshieldlib.lib.object.FabricShield.<init>(FabricShield.java:72) ~[Fabric-Shield-Lib-1.3.5-1.16.5.jar:?]
```

Cannot load class net.minecraft.client.world.ClientWorld in environment type SERVER
at me.crimsondawn45.fabricshieldlib.lib.object.FabricShield.<init>(FabricShield.java:72) ~[Fabric-Shield-Lib-1.3.5-1.16.5.jar:?]

My fabric mod json
```json
{
  "schemaVersion": 1,
  "id": "moreshields",
  "version": "${version}",
  "name": "MoreShields",
  "description": "A mod that utilizes fabric shield lib to add diamond, netherite and other shields!",
  "authors": [
    "px01tv"
  ],
  "contact": {
    "website": "https://github.com/px01tv/MoreShields",
    "repo": "https://github.com/px01tv/MoreShields"
  },
  "license": "MPL-2.0",
  "icon": "assets/moreshields/logo.png",
  "environment": "*",
  "entrypoints": {
    "main": [
      "io.px.moreshields.MoreShields"
    ]
  },
  "mixins": [
    "MoreShields.mixins.json"
  ],
  "depends": {
    "fabricloader": "\u003e\u003d0.11.1",
    "fabric": "*",
    "minecraft": "1.16.x"
  },
  "custom": {
    "modmenu": {
      "badges": [],
      "links": {
        "modmenu.discord": "https://discord.gg/n6XszBTAqv"
      }
    }
  }
}
```

My mod init and items class:

```java
@Override
    public void onInitialize() {
        ShieldItems.init();
    }
    ...
public static final Item PLATED_SHIELD = register( "plated_shield", new FabricShield(new Item.Settings().group( ItemGroups.SHIELD_GROUP ), 5, 420, 9, ItemTags.PLANKS ));
```

**Comment by px01tv** [comment]
Temporary release until PR gets merged: https://jitpack.io/#px01tv/Fabric-Shield-Lib/patch-1-SNAPSHOT
