### ISSUE TITLE
RuntimeException: Failed to read accessWidener file from mod fabricshieldlib

### ISSUE THREAD

**Issue by JustFoxx** [CrimsonDawn45/Fabric-Shield-Lib#78]
Issues in latst update of library
```java
java.lang.RuntimeException: Failed to read accessWidener file from mod fabricshieldlib
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
	... 3 more
```

**Comment by CrimsonDawn45** [comment]
Thanks for posting the error. I was looking through the mod and found the mistake. So when the next version comes out it should actually work lol.
