### ISSUE TITLE
Shield enchant target is broken outside dev environment / Reflection Enchantment Broken

### ISSUE THREAD

**Issue by CrimsonDawn45** [CrimsonDawn45/Fabric-Shield-Lib#82]
Shield enchantments cause crashes outside the development environment in 1.5.3-1.18. in 1.18.2
```
[12:24:41] [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
java.lang.AbstractMethodError: Receiver class net.minecraft.enchantment.EnchantmentTarget$15 does not define or inherit an implementation of the resolved method 'abstract boolean isAcceptableItem(net.minecraft.item.Item)' of abstract class net.minecraft.enchantment.EnchantmentTarget.
	at net.minecraft.enchantment.Enchantment.isAcceptableItem(Enchantment.java:121) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.command.EnchantCommand.execute(EnchantCommand.java:48) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.command.EnchantCommand.method_13240(EnchantCommand.java:35) ~[minecraft-project-@-merged-named.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager.java:222) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler.java:1134) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler.java:1120) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onChatMessage(ServerPlayNetworkHandler.java:1106) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket.java:48) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket.java:31) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:26) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:22) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:150) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:29) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:787) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1751) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:126) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:772) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:768) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:134) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:751) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:687) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:293) ~[minecraft-project-@-merged-named.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by CrimsonDawn45** [comment]
I'm not sure how to fix this this error only occurs in the development environment. Outside the development environment the enchantments work just fine.

**Comment by ExDrill** [comment]
After further investigation, it just crashes if the game loads anything that is having an enchantment applied onto it. I believe it might have to do with the new enchantment target being added.

**Comment by Desynq** [comment]
So, I may have come up with a ***very*** hacky solution.

![image](https://user-images.githubusercontent.com/69401694/174922291-46a21740-1b66-4d40-a25e-9b05ae6be87f.png)
![image](https://user-images.githubusercontent.com/69401694/174922362-383ff41e-87b8-4965-9810-e8b16071e324.png)

You can effectively include the this library's `ShieldTarget.java` into its own little square alongside its required classes with its mixin, `EnchantmentTargetMixin.java`, registered within your own mod's fabric.mod.json.

This seems to completely circumvent the crash associated with placing an item inside an enchanting table while in a development environment.

I guess this hack can kind of give some insight into how Fabric-ASM is handled in development environments or something along those lines. I would probably suggest excluding this hack from production releases of any mod you use for obvious reasons.

**Comment by CrimsonDawn45** [comment]
> I'm not entirely sure what this means we will have to do but I found a reference to AbstractMethodError in FabricASM https://github.com/Chocohead/Fabric-ASM
> 
> This is taken from that github repo's readme
> 
> "Landing Amphibiously There are times when a jetty alone is insufficient for the extension task at hand, resulting in big problems for any added values. In such situations a full amphibious landing to the cove's shore can be performed instead.
> 
> Any situation where a method in the enum needs to be subclasses, such as an abstract enum, adding values directly will result in AbstractMethodErrors when the methods are called for the added values. The constructor alone is unable to provide a solution to this; hence MM allows subclassing enums for added entries. These subclasses are defined via an additional structure class (to the constructor's parameters) which defines the overrides a subclass would like to make to the enum. Like normal addition there are two options depending how the normal constructor parameters are passed:"

Just Copying some notes from the duplicate issue over here

**Comment by CrimsonDawn45** [comment]
idk I'm not entirely sure how to fix this Issue I'll have to do a lot more research as my knowledge of FabricASM was just enough for me to initially get the enchantment target working.

**Comment by CrimsonDawn45** [comment]
I think I may have found the solution

**Comment by xanthian** [comment]
having a similar issue
I was convinced it was something to do with my custom bows, but I believe it could be this.
I've stripped my mod apart trying to root out this issue.


```
java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean isAcceptableItem(net.minecraft.item.Item)' of abstract class net.minecraft.enchantment.EnchantmentTarget.
	at net.minecraft.enchantment.EnchantmentHelper.getPossibleEntries(EnchantmentHelper.java:416)
	at net.minecraft.enchantment.EnchantmentHelper.generateEnchantments(EnchantmentHelper.java:365)
	at net.minecraft.enchantment.EnchantmentHelper.enchant(EnchantmentHelper.java:323)
	at net.minecraft.entity.mob.MobEntity.enchantMainHandItem(MobEntity.java:1061)
	at net.minecraft.entity.mob.MobEntity.updateEnchantments(MobEntity.java:1049)
	at net.minecraft.entity.mob.AbstractSkeletonEntity.initialize(AbstractSkeletonEntity.java:154)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:295)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:212)
	at net.minecraft.world.SpawnHelper.spawn(SpawnHelper.java:200)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager.java:376)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:323)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:319)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.enchantment.EnchantmentHelper.getPossibleEntries(EnchantmentHelper.java:416)
	at net.minecraft.enchantment.EnchantmentHelper.generateEnchantments(EnchantmentHelper.java:365)
	at net.minecraft.enchantment.EnchantmentHelper.enchant(EnchantmentHelper.java:323)
	at net.minecraft.entity.mob.MobEntity.enchantMainHandItem(MobEntity.java:1061)
	at net.minecraft.entity.mob.MobEntity.updateEnchantments(MobEntity.java:1049)
	at net.minecraft.entity.mob.AbstractSkeletonEntity.initialize(AbstractSkeletonEntity.java:154)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:295)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:212)
	at net.minecraft.world.SpawnHelper.spawn(SpawnHelper.java:200)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager.java:376)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:323)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:319)

```

**Comment by xanthian** [comment]
This is still occurring even with the latest patch
`dependencies {
	// Fabric Shield Lib
	modImplementation 'com.github.CrimsonDawn45:Fabric-Shield-Lib:v1.6.1-pre1-1.19'
}`

`
Time: 2022-09-30 20:07:23
Description: Exception ticking world

java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean isAcceptableItem(net.minecraft.item.Item)' of abstract class net.minecraft.enchantment.EnchantmentTarget.
	at net.minecraft.enchantment.EnchantmentHelper.getPossibleEntries(EnchantmentHelper.java:416)
	at net.minecraft.enchantment.EnchantmentHelper.generateEnchantments(EnchantmentHelper.java:365)
	at net.minecraft.enchantment.EnchantmentHelper.enchant(EnchantmentHelper.java:323)
	at net.minecraft.entity.mob.MobEntity.enchantMainHandItem(MobEntity.java:1061)
	at net.minecraft.entity.mob.MobEntity.updateEnchantments(MobEntity.java:1049)
	at net.minecraft.entity.mob.AbstractSkeletonEntity.initialize(AbstractSkeletonEntity.java:154)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:295)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:212)
	at net.minecraft.world.SpawnHelper.spawn(SpawnHelper.java:200)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager.java:376)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:323)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:319)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.enchantment.EnchantmentHelper.getPossibleEntries(EnchantmentHelper.java:416)
	at net.minecraft.enchantment.EnchantmentHelper.generateEnchantments(EnchantmentHelper.java:365)
	at net.minecraft.enchantment.EnchantmentHelper.enchant(EnchantmentHelper.java:323)
	at net.minecraft.entity.mob.MobEntity.enchantMainHandItem(MobEntity.java:1061)
	at net.minecraft.entity.mob.MobEntity.updateEnchantments(MobEntity.java:1049)
	at net.minecraft.entity.mob.AbstractSkeletonEntity.initialize(AbstractSkeletonEntity.java:154)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:295)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:212)
	at net.minecraft.world.SpawnHelper.spawn(SpawnHelper.java:200)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager.java:376)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:323)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:319)
`

**Comment by CrimsonDawn45** [comment]
I will probably have to do something similar to veinminer & see if I can do this without FabricASM

**Comment by xanthian** [comment]
any eta on a fix for this? literally cannot test anything in dev because of crashes.
or even a work around I can implement.
please. 🥺

**Comment by CrimsonDawn45** [comment]
I don't think I will have a fix anytime soon things in my life have gotten much MUCH more complicated lately. I don't have the time nor energy to maintain this project anymore.

**Comment by CrimsonDawn45** [comment]
The only way I've seen to fix this is to remove custom shield enchantment support temporarily
