### ISSUE TITLE
Crash on Fabric Loader 0.14.3

### ISSUE THREAD

**Issue by Fourbo** [CrimsonDawn45/Fabric-Shield-Lib#89]
I discovered that Minecraft crashes when Fabric Loader updated to 0.14.3 with this mod included. The crash log is from my Exaroton server, and it also crashes when replicated with Minecraft on the client. The mod worked fine with Fabric Loader 0.14.2.

**Mods Tested:**
fabric-api-0.51.1+1.18.2.jar
FabricShieldLib-1.5.3-1.18.jar

**Crash log:**
<html>
<body>

[18:25:27] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.3
--
2 | [18:25:27] [main/INFO]: Loading 39 mods:
3 | - cloth-basic-math 0.6.0 via cloth-config
4 | - cloth-config 6.2.57 via fabricshieldlib
5 | - fabric 0.51.1+1.18.2
6 | - fabric-api-base 0.4.4+d7c144a860 via fabric
7 | - fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
8 | - fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
9 | - fabric-command-api-v1 1.1.9+d7c144a860 via fabric
10 | - fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
11 | - fabric-containers-v0 0.1.21+d7c144a860 via fabric
12 | - fabric-content-registries-v0 3.0.3+d82b939260 via fabric
13 | - fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
14 | - fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
15 | - fabric-dimensions-v1 2.1.17+2540745460 via fabric
16 | - fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
17 | - fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
18 | - fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
19 | - fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
20 | - fabric-item-api-v1 1.4.0+4457765560 via fabric
21 | - fabric-item-groups-v0 0.3.11+91896a4960 via fabric
22 | - fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
23 | - fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
24 | - fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
25 | - fabric-networking-api-v1 1.0.21+d882b91560 via fabric
26 | - fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
27 | - fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
28 | - fabric-particles-v1 0.2.12+526dc1ac60 via fabric
29 | - fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
30 | - fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
31 | - fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
32 | - fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
33 | - fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
34 | - fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
35 | - fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
36 | - fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
37 | - fabricloader 0.14.3
38 | - fabricshieldlib 1.5.3-1.18
39 | - java 17
40 | - minecraft 1.18.2
41 | - mm 2.3 via fabricshieldlib
42 | [18:25:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
43 | [18:25:27] [main/INFO]: Compatibility level set to JAVA_16
44 | [18:25:27] [main/INFO]: Compatibility level set to JAVA_17
45 | [18:25:34] [main/ERROR]: Minecraft has crashed!
46 | net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
47 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.3.jar:?]
48 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.3.jar:?]
49 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.3.jar:?]
50 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
51 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
52 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
53 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
54 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.3.jar:?]
55 | Caused by: java.lang.ExceptionInInitializerError
56 | at net.minecraft.class_2378.method_10243(class_2378.java:190) ~[server-intermediary.jar:?]
57 | at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
58 | at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
59 | at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
60 | at net.minecraft.class_2378.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
61 | at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
62 | at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
63 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
64 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
65 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
66 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
67 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
68 | ... 7 more
69 | Caused by: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.util.UrlConversionException: java.net.MalformedURLException: unknown protocol: magic-at
70 | at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51) ~[fabric-loader-0.14.3.jar:?]
71 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:500) ~[fabric-loader-0.14.3.jar:?]
72 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:350) ~[fabric-loader-0.14.3.jar:?]
73 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:325) ~[fabric-loader-0.14.3.jar:?]
74 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
75 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
76 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
77 | at net.minecraft.class_1900.<init>(class_1900.java:36) ~[server-intermediary.jar:?]
78 | at net.minecraft.class_1893.<clinit>(class_1893.java:15) ~[server-intermediary.jar:?]
79 | at net.minecraft.class_2378.method_10243(class_2378.java:190) ~[server-intermediary.jar:?]
80 | at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
81 | at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
82 | at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
83 | at net.minecraft.class_2378.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
84 | at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
85 | at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
86 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
87 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
88 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
89 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
90 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
91 | ... 7 more
92 | Caused by: net.fabricmc.loader.impl.util.UrlConversionException: java.net.MalformedURLException: unknown protocol: magic-at
93 | at net.fabricmc.loader.impl.util.UrlUtil.getCodeSource(UrlUtil.java:48) ~[fabric-loader-0.14.3.jar:?]
94 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:498) ~[fabric-loader-0.14.3.jar:?]
95 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:350) ~[fabric-loader-0.14.3.jar:?]
96 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:325) ~[fabric-loader-0.14.3.jar:?]
97 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
98 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
99 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
100 | at net.minecraft.class_1900.<init>(class_1900.java:36) ~[server-intermediary.jar:?]
101 | at net.minecraft.class_1893.<clinit>(class_1893.java:15) ~[server-intermediary.jar:?]
102 | at net.minecraft.class_2378.method_10243(class_2378.java:190) ~[server-intermediary.jar:?]
103 | at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
104 | at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
105 | at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
106 | at net.minecraft.class_2378.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
107 | at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
108 | at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
109 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
110 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
111 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
112 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
113 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
114 | ... 7 more
115 | Caused by: java.net.MalformedURLException: unknown protocol: magic-at
116 | at java.net.URL.<init>(URL.java:480) ~[?:?]
117 | at java.net.URL.<init>(URL.java:365) ~[?:?]
118 | at net.fabricmc.loader.impl.util.UrlUtil.getCodeSource(UrlUtil.java:42) ~[fabric-loader-0.14.3.jar:?]
119 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:498) ~[fabric-loader-0.14.3.jar:?]
120 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:350) ~[fabric-loader-0.14.3.jar:?]
121 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:325) ~[fabric-loader-0.14.3.jar:?]
122 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
123 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
124 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
125 | at net.minecraft.class_1900.<init>(class_1900.java:36) ~[server-intermediary.jar:?]
126 | at net.minecraft.class_1893.<clinit>(class_1893.java:15) ~[server-intermediary.jar:?]
127 | at net.minecraft.class_2378.method_10243(class_2378.java:190) ~[server-intermediary.jar:?]
128 | at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
129 | at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
130 | at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
131 | at net.minecraft.class_2378.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
132 | at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
133 | at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
134 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
135 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
136 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
137 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
138 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
139 | ... 7 more

</body>
</html>[18:25:27] [main/INFO]: Loading Minecraft 1.18.[2](https://exaroton.com/log/#L2) with Fabric Loader 0.14.3
[18:25:27] [main/INFO]: Loading [3](https://exaroton.com/log/#L3)9 mods:
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57 via fabricshieldlib
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.[4](https://exaroton.com/log/#L4).4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a[5](https://exaroton.com/log/#L5)45[6](https://exaroton.com/log/#L6)0 via fabric
	- fabric-biome-api-v1 8.0.4+[7](https://exaroton.com/log/#L7)b0f312660 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a[8](https://exaroton.com/log/#L8)60 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b[9](https://exaroton.com/log/#L9)39260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.3
	- fabricshieldlib 1.5.3-1.18
	- java 17
	- minecraft 1.18.2
	- mm 2.3 via fabricshieldlib
[18:25:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[18:25:27] [main/INFO]: Compatibility level set to JAVA_16
[18:25:27] [main/INFO]: Compatibility level set to JAVA_17
[18:25:34] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:67) [fabric-loader-0.14.3.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2378.method_[10](https://exaroton.com/log/#L10)243(class_2378.java:190) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_[12](https://exaroton.com/log/#L12)851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.[14](https://exaroton.com/log/#L14).3.jar:?]
	... 7 more
Caused by: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.util.UrlConversionException: java.net.MalformedURLException: unknown protocol: magic-at
	at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:500) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:350) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:325) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1900.<init>(class_1900.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_1893.<clinit>(class_1893.java:[15](https://exaroton.com/log/#L15)) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10243(class_2378.java:190) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
	... 7 more
Caused by: net.fabricmc.loader.impl.util.UrlConversionException: java.net.MalformedURLException: unknown protocol: magic-at
	at net.fabricmc.loader.impl.util.UrlUtil.getCodeSource(UrlUtil.java:48) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:498) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:350) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:325) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:2[18](https://exaroton.com/log/#L18)) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_[19](https://exaroton.com/log/#L19)00.<init>(class_1900.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_1893.<clinit>(class_1893.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10243(class_2378.java:190) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
	... 7 more
Caused by: java.net.MalformedURLException: unknown protocol: magic-at
	at java.net.URL.<init>(URL.java:480) ~[?:?]
	at java.net.URL.<init>(URL.java:365) ~[?:?]
	at net.fabricmc.loader.impl.util.UrlUtil.getCodeSource(UrlUtil.java:42) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getCodeSource(KnotClassDelegate.java:498) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getMetadata(KnotClassDelegate.java:350) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:325) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:5[20](https://exaroton.com/log/#L20)) ~[?:?]
	at net.minecraft.class_1900.<init>(class_1900.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_1893.<clinit>(class_1893.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_10243(class_2378.java:190) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40280(class_2378.java:352) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_34031(class_2378.java:300) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:7[21](https://exaroton.com/log/#L21)) ~[?:?]
	at net.minecraft.class_[23](https://exaroton.com/log/#L23)78.<clinit>(class_2378.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_1[28](https://exaroton.com/log/#L28)51(class_[29](https://exaroton.com/log/#L29)66.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:[43](https://exaroton.com/log/#L43)) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:[45](https://exaroton.com/log/#L45)2) ~[fabric-loader-0.14.3.jar:?]
	... 7 more

**Comment by Footage2-Amply-Pounce** [comment]
Fixed in Fabric Loader 0.14.4.

**Comment by CringeStar** [comment]
as i see this has fixed, please close this issue
